databases:
  - name: micronaut
    databaseName: micronaut_aa81
    user: micronaut_aa81_user

services:
  - type: web
    name: wilhelm-budget-app
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: micronaut
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
